universe = vanilla

InitialDir = /u/kyeh/cs/nlp-sentence-compression
Executable = berkeleyaligner/align

+Group = "GRAD"
+Project = "INSTRUCTIONAL"
+ProjectDescription = "CS388 Sentence Compression"

Log = /u/kyeh/cs/NLP/p3/condor/logs/europarl-de.log

Notification = complete
Notify_user = kevinyeah@utexas.edu

Arguments = ../alignment/europarl.de-en.conf

Output = condor/logs/europarl.de.out
Error  = condor/logs/europarl.de.err
Queue 1
