universe = vanilla

InitialDir = /u/kyeh/cs/nlp-sentence-compression/berkeleyaligner
Executable = ./align

+Group = "GRAD"
+Project = "INSTRUCTIONAL"
+ProjectDescription = "CS388 Sentence Compression"

Log = ../condor/logs/news-commentary-de.log

Notification = complete
Notify_user = kevinyeah@utexas.edu

Arguments = alignment/news-commentary.de-en.conf

Output = ../condor/logs/news-commentary.de.out
Error  = ../condor/logs/news-commentary.de.err
Queue 1
